spring:
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/campuscart?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
logging:
  level:
    root: INFO
server:
  port: 8080